# Generated by Django 5.0 on 2023-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
