# Generated by Django 5.0 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0002_alter_tasktable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
